name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Load environment variables
        run: |
          if [ -f .env ]; then
            echo "Loading environment variables from .env"
            export $(grep -v '^#' .env | xargs)
            printenv | grep -E 'DB_HOST|DB_PORT|DB_NAME|DB_USERNAME|DB_PASSWORD' >> $GITHUB_ENV
          fi

      - name: Install Podman and Podman-Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y podman podman-compose

      - name: Set Podman runtime to runc
        run: |
          if [ ! -f /etc/containers/containers.conf ]; then
            echo "Creating default containers.conf"
            sudo mkdir -p /etc/containers
            echo -e "[engine]\nruntime = \"runc\"" | sudo tee /etc/containers/containers.conf > /dev/null
          else
            sudo sed -i 's/^runtime = "crun"/runtime = "runc"/' /etc/containers/containers.conf
          fi
          sudo systemctl restart podman

      - name: Set temporary directory for Podman
        run: |
          export TMPDIR=/tmp
          echo "export TMPDIR=/tmp" >> $GITHUB_ENV

      - name: Start services with Podman-Compose
        run: |
          export COMPOSE_FILE=podman-compose.yaml
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          sudo podman-compose --env-file .env up -d
        working-directory: .

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            sudo podman exec postgres-container psql -U ${DB_USERNAME} -d ${DB_NAME} -c "SELECT 1" && echo "PostgreSQL is ready" && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
          echo "PostgreSQL failed to start" && exit 1

      - name: Run tests
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          SPRING_PROFILES_ACTIVE: test
        run: mvn test -X

      - name: Stop services
        if: always()
        run: sudo podman-compose down